### ================================================
###              FLUXO DE AUTENTICAÇÃO
### ================================================

# Cadastrar um novo entregador
POST http://localhost:3000/auth/cadastro
Content-Type: application/json

{
  "nome_completo": "Fabio Rocha",
  "cpf": "08791127513",
  "email": "fabio.rocha@a.ucb.br",
  "senha": "minhasenha",
  "endereco": "CSG 03, DF",
  "telefone": "77998205373"
}

###

# Realizar login de um entregador
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "cpf": "08791127513",
  "senha": "minhasenha"
}

### ================================================
###                FLUXO DE MOTOS
### ================================================

# Cadastrar uma nova moto para um entregador
# Substitua {{entregadorId}} pelo ID de um entregador existente
POST http://localhost:3000/moto/entregador/{{entregadorId}}
Content-Type: application/json

{
  "modelo": "Honda CG 160 Titan",
  "placa": "BRA2E19",
  "cor": "Vermelha",
  "ano_fabricacao": 2023
}

###

# Buscar todas as motos de um entregador
# Substitua {{entregadorId}} pelo ID de um entregador existente
GET http://localhost:3000/moto/entregador/{{entregadorId}}

### ================================================
###                FLUXO DE PEDIDOS
### ================================================

# Criar pedidos de teste (Seed)
# Popular o banco de dados para testes
POST http://localhost:3000/pedidos/seed/{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}

###

# Após rodar o seed, use esta rota para ver os pedidos e copiar o "id" de um deles
GET http://localhost:3000/pedidos/disponiveis

###

# Marcar um pedido como entregue
# Esta ação remove o pedido do mural de disponíveis e o associa ao seu entregador.
PATCH http://localhost:3000/pedidos/{{COLAR O NUMERO DO ID DO PEDIDO AQUI}}/entregue
Content-Type: application/json

{
  "entregadorId": "{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}"
}

###

# Ver o histórico de pedidos de um entregador
GET http://localhost:3000/pedidos/historico/{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}

### ================================================
###                FLUXO DE MÉTRICAS E GRÁFICOS
### ================================================

# Obter as métricas do Dashboard para o seu entregador
GET http://localhost:3000/pedidos/metricas/{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}

# Obter dados para o gráfico de Renda Mensal
GET http://localhost:3000/pedidos/grafico/renda-mensal/{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}

# Obter dados para o gráfico de Quilometragem Semanal
GET http://localhost:3000/pedidos/grafico/quilometragem/{{COLAR O NUMERO DO ID DO ENTREGADOR AQUI}}